### ISSUE TITLE
v4 Feedback thread

### ISSUE THREAD

**Issue by eramdam** [eramdam/BetterTweetDeck#533]
# 📣

I'm very close to shipping Better TweetDeck 4 and I need folks to test it to see if everything works fine.

If you're interested in testing, please grab the appropriate version for your browser, run it, and comment in this thread if you find anything broken!

[better-tweetdeck-4.0.0.chrome.zip](https://github.com/eramdam/BetterTweetDeck/files/6206209/better-tweetdeck-4.0.0.chrome.zip)
[better-tweetdeck-4.0.0.firefox.zip](https://github.com/eramdam/BetterTweetDeck/files/6206210/better-tweetdeck-4.0.0.firefox.zip)
[better-tweetdeck-4.0.0.safari.zip](https://github.com/eramdam/BetterTweetDeck/files/6206211/better-tweetdeck-4.0.0.safari.zip)

A few notes:

- The Chrome version can and will run on Opera/New Edge just fine.
- You will need to load the extension as unpacked in Chrome/Edge/Opera/Firefox
  - [Instructions for Firefox](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)
  - [Instructions for Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)
  - [Instructions for Chrome](https://developer.chrome.com/docs/extensions/mv2/getstarted/#manifest) (see second part of "Create the manifest" step)
  - [Instructions for Opera](https://dev.opera.com/extensions/basics/#step-4-testing-your-extension) (step 4)
- As far as I can tell the Safari version should be properly signed, let me know if it is not.
- If you're interested in translating the extension into your language, please ping me! I'll tackle the French translation before/shortly after release but I know I'll need help for locales that were previously supported.
- I'm considering v4.0.0 to be feature frozen. Meaning that I won't add any features to it. Anything new will come in subsequent versions. I need feedbacks about bugs/things broken.
- **If you agree with a specific comment, use the emoji reactions to keep the thread clean.**

# Changelog

This work was done over the span of 2 years so I'm probably forgetting some details, but I truly believe it is for the best and Better TweetDeck will be made even better (eh) for it.

## Misc

Better TweetDeck was completely rewritten from scratch using modern tooling:

- The codebase is using fully using TypeScript.
- The UI elements injected into TweetDeck use [`dom-chef`](https://github.com/vadimdemedes/dom-chef) or [React](https://reactjs.org)
- The settings page is fully built using React
- The tooling uses Webpack 5 and the TypeScript compiler for JS transpiling
- Most if not all features have been rewritten, fixing a lot of small bugs I never had time to tackle or just improve them in some ways

All of those changes were made for a couple of reasons:

- Makes the codebase easier to maintain
- Makes BTD lighter/faster (I haven't made actual measurements but less code is always faster to run :P)

## New things/features

- Completely new UI for the settings
  - There's an import/export feature (fixes https://github.com/eramdam/BetterTweetDeck/issues/467)
- Possibility to change the accent color
- A new "Super Black" theme
- A "new" "Old Gray" theme (which replaces the related setting in v3)
- Can choose to switch between a dark theme and the light theme automatically following your OS' settings (fixes https://github.com/eramdam/BetterTweetDeck/issues/497)
- Single images can be shown with their original aspect ratio (fixes https://github.com/eramdam/BetterTweetDeck/issues/525)
- Tweet "cards" (link previews) can be shown in the columns (sorta fixes https://github.com/eramdam/BetterTweetDeck/issues/515)
- You can choose to display the "like from accounts..." dialog when clicking the like button (fixes https://github.com/eramdam/BetterTweetDeck/issues/486)
- You can add a "Delete" button on top of columns (fixes https://github.com/eramdam/BetterTweetDeck/issues/241)
- Quote tweets with images are displayed like on Twitter Web (semi-fix for https://github.com/eramdam/BetterTweetDeck/issues/531)
- You can display fullscreen images like on Twitter Web (fixes https://github.com/eramdam/BetterTweetDeck/issues/488)
- BTD updates the regex used for Twemoji (= TweetDeck can properly display newer emojis)
- You can add a "Remove" button to each column (fixes https://github.com/eramdam/BetterTweetDeck/issues/482)
- Make Trending column collapsable (partly fixes https://github.com/eramdam/BetterTweetDeck/issues/382)
- Fix thinner scrollbars on Trending column (fixes https://github.com/eramdam/BetterTweetDeck/issues/527)

## Improvements on existing features

- The emoji picker now uses [emoji-mart](https://github.com/missive/emoji-mart) instead of being 100% custom
  - The emoji auto-completion also uses emoji-mart for its data
  - The emoji list aren't completely up-to-date. emoji-mart hasn't updated and I don't know yet if I can update the data independently so this will be done later one
- The "verified badge" setting now can show both verified AND translator badges
- The "Old Gray" theme was made from the ground up. It's not a 100% reproduction anymore but it will be much easier for me to maintain.
- The Custom CSS setting now uses the [Monaco](https://microsoft.github.io/monaco-editor/index.html) editor, which should provide a better experience when editing code in there.

## Removed (because obsolete/not used a lot)

If you somehow **really** depend on a given removed feature, comment about it and I can try to squeeze it in a future v4 release.

### Applied by default

- Removed the "When you collapse a column, it will pause the feed it so that it can light up when its contents change while collapsed and it stays where you last saw it" (applied by default)
- Removed the "When you uncollapse a column, it will unpause the feed it so that it automatically scrolls back to the top instead of staying where you left it" (applied by default)
- BTD's logo is always applied in the bottom left corner

### Made obsolete by TweetDeck

- Removed the "Hide in reply to label on mentions" feature
- Removed the "use the system font in the UI" setting since TweetDeck does it natively

### Removed for other reasons

- Image/video/audio thumbnails. See reasoning in https://twitter.com/BetterTDeck/status/1366974655077097473. They're made obsolete by the link preview feature IMO.
- Removed the "make tweets flash" feature
- Removed the "Holding Ctrl (or Cmd on Mac) while clicking: favorite / retweet / download will allow you to follow from the" feature

### Not present right now but will be brought back

- The "share on TweetDeck" contextual menu item isn't enabled yet. I'll re-add settings for it at a later time (I barely use it so I didn't notice it until yesterday...)

**Comment by Neurotoxin001** [comment]
Can you please provide changelog for v.4?

**Comment by eramdam** [comment]
> Can you please provide changelog for v.4?

Good call. Will update the main comment 😁

**Comment by ThibautPlg** [comment]
I've just installed it and will report any problems. At first glance, everything looks fine tbh !
I've just noticed a missing translation on the "General settings" tab : 
- "Display fullscreen images à la Twitter Web"

**Comment by eramdam** [comment]
> I've just installed it and will report any problems. At first glance, everything looks fine tbh !
> I've just noticed a missing translation on the "General settings" tab :
> 
> * "Display fullscreen images à la Twitter Web"

How does it show up(or not)? I haven't added any non-English locales yet so i'm curious to see what you saw 🙈

**Comment by jaxidian** [comment]
Should I be able to mute/block myself? I get those options on my tweets (or duplicates of my tweets from likes/RTs). I would think those buttons shouldn't be there for myself.

**Comment by jaxidian** [comment]
![image](https://user-images.githubusercontent.com/260128/111205930-265eb500-859e-11eb-83b6-7407fc2ec278.png)

**Comment by NitroxydeX** [comment]
I'm using Chrome Version 89.0.4389.90 
- "Style of scrollbars" under Settings -> Theme doesn't do anything. It stays on it's default size.
- Emoji-picker closes most of the time when clicking on the emoji category.

**Comment by ThibautPlg** [comment]
> 
> 
> > I've just installed it and will report any problems. At first glance, everything looks fine tbh !
> > I've just noticed a missing translation on the "General settings" tab :
> > 
> > * "Display fullscreen images à la Twitter Web"
> 
> How does it show up(or not)? I haven't added any non-English locales yet so i'm curious to see what you saw 🙈

Okay mb, I'm dumber than I look. I'm not english native and didn't realize that "à la [smth]" is used in english. ¯\_(ツ)_/¯

**Comment by jaxidian** [comment]
> I'm using Chrome Version 89.0.4389.90
> 
> * "Style of scrollbars" under Settings -> Theme doesn't do anything. It stays on it's default size.
> * Emoji-picker closes most of the time when clicking on the emoji category.

Same, Edge Stable

**Comment by eramdam** [comment]
Please use the " 👍 " reaction on comments if you experience the same bugs 😄

**Comment by NitroxydeX** [comment]
Chrome Version 89.0.4389.90

There is also this error on the extensions page for btd v4

![image](https://user-images.githubusercontent.com/9305576/111207569-165cca80-85ca-11eb-9d5f-4ac5db6a09fc.png)

**Comment by jaxidian** [comment]
(Edge Stable)

Using this custom Date format, it seems to not apply until 2-10 seconds after a tweet loads. Specifically, when I do a hard refresh of the page, all dates are relative for about 10 seconds then the custom format applies. Monitoring my Home column, whenever a new tweet loads, it has a relative time and then the custom format loads 2-5s later.

Nothing exactly broken, just wanted to document this as a performance opportunity for later. :)

![image](https://user-images.githubusercontent.com/260128/111207558-29f33b80-85a0-11eb-9c91-56d72a55abf2.png)

**Comment by klec29** [comment]
Using Edge Stable

Collapsed columns aren't staying collapsed on refresh or browser restart

**Comment by NuclearMeltdown** [comment]
Scrollbar styles don't do anything.

**Comment by eramdam** [comment]
I'll have to hide comments that are duplicates. **Please** read the thread and use the 👍 reaction on comments if you experience the same bugs as them instead of posting a new comment. Thanks.

**Comment by jaxidian** [comment]
> I'll have to hide comments that are duplicates. **Please** read the thread and use the 👍 reaction on comments if you experience the same bugs as them instead of posting a new comment. Thanks.

Quick Q: Does this mean you do not want "me too but in a different browser, here are the details" types of posts but would rather just the 👍?

**Comment by eramdam** [comment]
> > I'll have to hide comments that are duplicates. **Please** read the thread and use the 👍 reaction on comments if you experience the same bugs as them instead of posting a new comment. Thanks.
> 
> Quick Q: Does this mean you do not want "me too but in a different browser, here are the details" types of posts but would rather just the 👍?

Yes. I'll try to troubleshoot any bug on all browsers so usually if something is ever browser-specific, I hopefully will run into it 😁

**Comment by Geobert** [comment]
Firefox Nightly
Great work, everything looks fine but for minor stuff like: 
Using thin scrollbar doesn't change the horizontal scrollbar

**Comment by raulcraveiro** [comment]
The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.

**Comment by eramdam** [comment]
> The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.

What do you mean by "smooth scroll"? 🤨

**Comment by raulcraveiro** [comment]
> > The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.
> 
> What do you mean by "smooth scroll"?

The way that the page moves when I scroll. I made a video to be more clear:

https://user-images.githubusercontent.com/5623492/111211680-74c78000-85ad-11eb-84cb-5fe02a10b037.mp4

**Comment by eramdam** [comment]
> > > The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.
> > 
> > 
> > What do you mean by "smooth scroll"?
> 
> The way that the page moves when I scroll. I made a video to be more clear:
> 
>  Untitled.mp4

Better TweetDeck shouldn't touch anything around that so it's odd... Can you double check if it happens with BTD disabled?

**Comment by jaxidian** [comment]
Feature Request (that I expect you to say "no thanks" to, but it never hurts to ask):

Allow me to show the "Clear" button ONLY at the top of a Search Results column, but not my other columns. I also wonder if I could accomplish this with some custom CSS. If I solve that, I'll post that here in case somebody else wants it. (And if you're in the market to purchase a new video card, you can probably guess my use case here.)

![image](https://user-images.githubusercontent.com/260128/111212982-abe66300-85a6-11eb-972c-bc5671f2ff7f.png)

**Comment by raulcraveiro** [comment]
> > > > The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.
> > > 
> > > 
> > > What do you mean by "smooth scroll"?
> > 
> > 
> > The way that the page moves when I scroll. I made a video to be more clear:
> > Untitled.mp4
> 
> Better TweetDeck shouldn't touch anything around that so it's odd... Can you double check if it happens with BTD disabled?

Apparently it doesn't have smooth scroll at all without the extension.

**Comment by eramdam** [comment]
> > > > > The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.
> > > > 
> > > > 
> > > > What do you mean by "smooth scroll"?
> > > 
> > > 
> > > The way that the page moves when I scroll. I made a video to be more clear:
> > > Untitled.mp4
> > 
> > 
> > Better TweetDeck shouldn't touch anything around that so it's odd... Can you double check if it happens with BTD disabled?
> 
> Apparently it doesn't have smooth scroll at all without the extension.

What the heck... Do you have the "Pause column scrolling on hover" setting enabled, by chance? I wonder if that's somehow related..

**Comment by raulcraveiro** [comment]
> > > > > > The smooth scroll is kinda inconsistent. Sometimes It stops working suddenly, sometimes It stops after you expand an image and the only solution is to reload the page.
> > > > > 
> > > > > 
> > > > > What do you mean by "smooth scroll"?
> > > > 
> > > > 
> > > > The way that the page moves when I scroll. I made a video to be more clear:
> > > > Untitled.mp4
> > > 
> > > 
> > > Better TweetDeck shouldn't touch anything around that so it's odd... Can you double check if it happens with BTD disabled?
> > 
> > 
> > Apparently it doesn't have smooth scroll at all without the extension.
> 
> What the heck... Do you have the "Pause column scrolling on hover" setting enabled, by chance? I wonder if that's somehow related..

No, It's disabled :/

**Comment by jaxidian** [comment]
(Edge Stable)

The scrollbar is placed incorrectly in the inline compose window when replying to tweets in a column:
![image](https://user-images.githubusercontent.com/260128/111214854-d2a59900-85a8-11eb-9078-71e4dc358c1a.png)

These are my sizing settings (no custom CSS nor custom column width outside of these settings):
![image](https://user-images.githubusercontent.com/260128/111214942-ec46e080-85a8-11eb-8495-02e66ab2de72.png)

**Comment by jaxidian** [comment]
(Edge Stable)

Multiple Custom CSS classes/selectors are not working. If I remove either selector and include just the other, they both work (individually). But when they're both in there at the same time, neither are applied correctly.

![image](https://user-images.githubusercontent.com/260128/111221398-d2a99700-85b0-11eb-833b-236f2143e7d7.png)

**Comment by eramdam** [comment]
@NitroxydeX @jaxidian @klec29 @raulcraveiro I fixed the issue you all reported. Check the main comment for updated builds 🙇‍♂️

**Comment by Neurotoxin001** [comment]
Can you please move emoji button to previous place? Here:

![image](https://user-images.githubusercontent.com/39812401/111263950-c583bb00-8637-11eb-908a-a7c6c7c1b20d.png)

Because now you have to get used to the new location.

**Comment by eramdam** [comment]
> Can you please move emoji button to previous place? Here:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/39812401/111263950-c583bb00-8637-11eb-908a-a7c6c7c1b20d.png)
> 
> 
> 
> Because now you have to get used to the new location.

No. I moved it higher because the previous location made it hard to use for folks who had a smaller screen.

**Comment by jaxidian** [comment]
I've retested most of my findings and they largely look fixed! Well done, and thanks!

I know you acknowledged it on Twitter but just to be sure it gets logged here so it's easier for you to track, there's also the Dagger problem (that used to be the Doctor problem):

![image](https://user-images.githubusercontent.com/260128/111345110-574cf180-8653-11eb-95d0-bf494a4726e5.png)

**Comment by eramdam** [comment]
> I've retested most of my findings and they largely look fixed! Well done, and thanks!
> 
> I know you acknowledged it on Twitter but just to be sure it gets logged here so it's easier for you to track, there's also the Dagger problem (that used to be the Doctor problem):
> 
> ![image](https://user-images.githubusercontent.com/260128/111345110-574cf180-8653-11eb-95d0-bf494a4726e5.png)

Argh. I thought I fixed it but my fix was too simplistic 🙈

**Comment by NitroxydeX** [comment]
Seems like the emoji-picker is still broken.
To make it absolutely clear here's a video of it:

https://ntrxydx.net/vTLdy

**Comment by eramdam** [comment]
Updated the builds in the main post with the following fixes:
- Fixed the emoji completion matching smilies that start by `:-` (cc @jaxidian) 
- Restored the "save tweeted hashtags" feature
- Restored the "add search columns first in the list" feature
- Made a small fix around the light/dark theme auto-switching
- Made some underlying changes to prepare showing a banner when BTD gets updated.

**Comment by eramdam** [comment]
Updated the builds in the main post with the following fixes:
- Fixed the emoji completion matching smilies that start by `:-` (cc @jaxidian) 
- Restored the "save tweeted hashtags" feature
- Restored the "add search columns first in the list" feature
- Made a small fix around the light/dark theme auto-switching
- Made some underlying changes to prepare showing a banner when BTD gets updated.


Thanks again all for testing and reporting these issues, it has been extremely helpful. I feel like I should be able to publish v4 publicly by the end of the month (as I need to prepare assets and update the website) 🙇‍♂️

**Comment by holly-macdonald** [comment]
![image](https://user-images.githubusercontent.com/59975854/111471406-1a7e0a80-86e6-11eb-8914-fb4c7cd6df81.png)

I just encountered a fullscreen image being cut off at the top when "Display fullscreen images à la Twitter Web" is enabled. https://twitter.com/ArchieComics/status/1371927216922234886 is the tweet, I'm running Firefox 85.0.2 on Windows 10

**Comment by NitroxydeX** [comment]
It seems like the gray style isn't applied to user profiles nor their user-tweets, mentions etc.

![image](https://user-images.githubusercontent.com/9305576/111531446-d716b100-8764-11eb-91e2-fc1b20b67e3d.png)
![image](https://user-images.githubusercontent.com/9305576/111531731-3674c100-8765-11eb-8a2b-0e90dc91456d.png)

**Comment by eramdam** [comment]
Updated the main post with new builds which:

- Fixes the issue you reported @holly-macdonald 
- Fixes the theme issue you reported @Neurotoxin001 (I tried to look for other places in the UI that didn't have the right color, it probably won't be perfect for the release date so it will be a game of whack-a-mole)
- Tweaks some logic around the badges on top of avatars

**Comment by Primeey** [comment]
This is extremely minor but also quite annoying. Is there any reason why tweets move up 1 pixel when I hover over them?

https://youtu.be/xi6Q07gBUxA

**Comment by eramdam** [comment]
> This is extremely minor but also quite annoying. Is there any reason why tweets move up 1 pixel when I hover over them?
> 
> https://youtu.be/xi6Q07gBUxA

The video is private but i might know what you're talking about. If you have the "Pause column scrolling on hover" option enabled, unfortunately that's how TweetDeck pauses the scrolling in columns, it applies a scrollTop of 1 (paused) or 0 (unpaused), so if you are at the very top of a column already then it will shift everything 😕

**Comment by Primeey** [comment]
> > This is extremely minor but also quite annoying. Is there any reason why tweets move up 1 pixel when I hover over them?
> > https://youtu.be/xi6Q07gBUxA
> 
> The video is private but i might know what you're talking about. If you have the "Pause column scrolling on hover" option enabled, unfortunately that's how TweetDeck pauses the scrolling in columns, it applies a scrollTop of 1 (paused) or 0 (unpaused), so if you are at the very top of a column already then it will shift everything 😕

That seems like a janky way to do it lol but yeah you're correct. As soon I disabled the option it no longer shifts. Wasn't aware that it's a tweetdeck problem and not a better tweetdeck problem. My apologise.

**Comment by eramdam** [comment]
> > > This is extremely minor but also quite annoying. Is there any reason why tweets move up 1 pixel when I hover over them?
> > > https://youtu.be/xi6Q07gBUxA
> > 
> > 
> > The video is private but i might know what you're talking about. If you have the "Pause column scrolling on hover" option enabled, unfortunately that's how TweetDeck pauses the scrolling in columns, it applies a scrollTop of 1 (paused) or 0 (unpaused), so if you are at the very top of a column already then it will shift everything 😕
> 
> That seems like a janky way to do it lol but yeah you're correct. As soon I disabled the option it no longer shifts. Wasn't aware that it's a tweetdeck problem and not a better tweetdeck problem. My apologise.

It really is, but i can't work around it since I just call the `pause`/`unpause` method on TweetDeck's columns and that what they do internally 😬 😂

**Comment by ngoo5tsong5sik** [comment]
![Screenshot_2021-03-19 TweetDeck](https://user-images.githubusercontent.com/16879992/111721423-d2ecaf80-889a-11eb-924e-90ae36419aef.png)
Themes aren't applied to Trending columns.

**Comment by eramdam** [comment]
> ![Screenshot_2021-03-19 TweetDeck](https://user-images.githubusercontent.com/16879992/111721423-d2ecaf80-889a-11eb-924e-90ae36419aef.png)
> Themes aren't applied to Trending columns.

Fixed in the newest build (see top comment) 🙇‍♂️

**Comment by Vitoire** [comment]
Heya!

First off - v4 looking mighty fine so far! The new "Old Gray" design looks super neat and I'm in love with it, really a huge improvement over the one we have over at v3. 
Thanks for all the hard work you put into this project!! Now, as for the reason why I'm here...

I remember that when you implemented the Block/Mute buttons, I poked you on Twitter about it, because this function wasn't working in the Activity column. It was quickly fixed in v3, but seems to be a returning bug in v4. If you try to block or mute someone from within the Activity column, nothing happens. 
Less important, but still worth mentioning - if you open a tweet within a column (any column in this case) and try to use the block or mute button, it also doesn't work. If these two issues could be fixed, that would be absolutely amazing!

**Comment by eramdam** [comment]
> Heya!
> 
> First off - v4 looking mighty fine so far! The new "Old Gray" design looks super neat and I'm in love with it, really a huge improvement over the one we have over at v3.
> Thanks for all the hard work you put into this project!! Now, as for the reason why I'm here...
> 
> I remember that when you implemented the Block/Mute buttons, I poked you on Twitter about it, because this function wasn't working in the Activity column. It was quickly fixed in v3, but seems to be a returning bug in v4. If you try to block or mute someone from within the Activity column, nothing happens.
> Less important, but still worth mentioning - if you open a tweet within a column (any column in this case) and try to use the block or mute button, it also doesn't work. If these two issues could be fixed, that would be absolutely amazing!
> 
> Edit: Search columns seem to act the same way, block/mute buttons don't work there.

Good catch, should be fixed in the newest build!

**Comment by eramdam** [comment]
Alright folks, thanks for helping me iron things out with v4 over the last few days, it has been very helpful!

I'll lock this thread because I'm getting ready to merging/releasing everything so I won't be touching the code until release.

Thanks! 🙇‍♂️
